[versions]
compose = "1.6.10-beta03"
compose-compiler = "2.0.0-RC3"
android-activityCompose = "1.8.2"
android-svg = "1.4"
android-lottie = "6.3.0"

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose-compiler" }

[libraries]
android-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "android-activityCompose" }
android-svg = { module = "com.caverock:androidsvg-aar", version.ref = "android-svg" }
android-lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "android-lottie" }
