name: build and publish a release

on:
  release:
    types: [published]

jobs:
  unit-tests:
    uses: kosi-libs/kodein-internal-github-actions/.github/workflows/unit-tests.yml@main
  build-upload:
    needs: [unit-tests]
    runs-on: macOS-latest
    env:
      CENTRAL_PORTAL_TOKEN_USERNAME: ${{ secrets.CENTRAL_PORTAL_TOKEN_USERNAME }}
      CENTRAL_PORTAL_TOKEN_PASSWORD: ${{ secrets.CENTRAL_PORTAL_TOKEN_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.PGP_SIGNING_KEY }}
      GPG_PRIVATE_PASSWORD: ${{ secrets.PGP_SIGNING_PASSWORD }}
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
        with:
          java-version: 21
      - name: Upload
        run: ./gradlew publishAggregationToCentralPortal
        shell: bash
