name: build and publish a release

on:
  release:
    types: [published]

jobs:
  create-staging-repository:
    uses: kosi-libs/kodein-internal-github-actions/.github/workflows/create-nexus-staging-repository.yml@main
    secrets: inherit

  build-upload:
    needs: create-staging-repository
    runs-on: macOS-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.PGP_SIGNING_KEY }}
      GPG_PRIVATE_PASSWORD: ${{ secrets.PGP_SIGNING_PASSWORD }}
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
      - name: Check
        run: ./gradlew --stacktrace check
        shell: bash
      - name: Upload
        run: ./gradlew --stacktrace publishAllPublicationsToOssrhStagingRepository -Porg.kodein.sonatype.repositoryId=${{ needs.create-staging-repository.outputs.repository-id }}
        shell: bash

  drop-or-release-staging-repository:
    needs: [create-staging-repository, build-upload]
    if: ${{ always() && needs.create-staging-repository.result == 'success' }}
    uses: kosi-libs/kodein-internal-github-actions/.github/workflows/drop-or-release-nexus-staging-repository.yml@main
    secrets: inherit
    with:
      repository-id: ${{ needs.create-staging-repository.outputs.repository-id }}
      build-upload-result: ${{ needs.build-upload.result }}
