name: check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'

jobs:
  check:
    runs-on: macOS-latest
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
        with:
          java-version: 21
      - name: Check
        run: ./gradlew --stacktrace check
        shell: bash
